# Generated by Django 3.2.25 on 2025-03-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('exam_date', models.CharField(max_length=200)),
                ('exam_time', models.CharField(max_length=200)),
                ('interview_date', models.CharField(max_length=200)),
                ('interview_time', models.CharField(max_length=200)),
                ('no_of_unknown_person', models.CharField(max_length=100)),
                ('multiple_person', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('lisence', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=700)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='question_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('option_A', models.CharField(max_length=200)),
                ('option_B', models.CharField(max_length=200)),
                ('option_C', models.CharField(max_length=200)),
                ('option_D', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vacancy_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_requirement', models.CharField(max_length=200)),
                ('apply_date', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('cuttoff', models.CharField(default=1, max_length=100)),
                ('COMPANY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.company_tb')),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.login_tb')),
            ],
        ),
        migrations.CreateModel(
            name='test_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('QUESTION', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.question_tb')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb')),
            ],
        ),
        migrations.CreateModel(
            name='review_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('COMPANY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.company_tb')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb')),
            ],
        ),
        migrations.AddField(
            model_name='question_tb',
            name='VACENCY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.vacancy_tb'),
        ),
        migrations.CreateModel(
            name='exam_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=200)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.candidate_tb')),
            ],
        ),
        migrations.CreateModel(
            name='emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.CharField(max_length=100)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb')),
            ],
        ),
        migrations.AddField(
            model_name='company_tb',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.login_tb'),
        ),
        migrations.CreateModel(
            name='chat_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('COMPANY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.company_tb')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb')),
            ],
        ),
        migrations.AddField(
            model_name='candidate_tb',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb'),
        ),
        migrations.AddField(
            model_name='candidate_tb',
            name='VACENCY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.vacancy_tb'),
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.CharField(max_length=20)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock_interview_app.user_tb')),
            ],
        ),
    ]
