# Generated by Django 3.2.25 on 2025-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_tb',
            name='interview_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate_tb',
            name='interview_time',
            field=models.TimeField(max_length=200),
        ),
    ]
