# Generated by Django 3.2.25 on 2025-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview_app', '0002_auto_20250306_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_tb',
            name='interview_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate_tb',
            name='interview_time',
            field=models.CharField(max_length=200),
        ),
    ]
